config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :shouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "shouts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :shout
end

app/models/shout.rb
class Shout < ApplicationRecord
    belongs_to :user
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
    has_many :comments, dependent: :destroy
>>>>>>> 294d7336c24df0edd0ccf35a7cee0ccca84a468e
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

<<<<<<< HEAD
      has_many :shouts
=======
<<<<<<< HEAD
         has_many :shouts
=======
      has_many :shouts
>>>>>>> 294d7336c24df0edd0ccf35a7cee0ccca84a468e
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @shout = Shout.find(params[:shout_id])
        @comment = @shout.comments.create(params[:comment].permit(:name, :comment))
        redirect_to shout_path(@shout)
    end

    def destroy
        @shout = Shout.find(params[:shout_id])
        @comment = @shout.comments.find(params[:id])
        @comment.destroy
        redirect_to shout_path(@shout)
    end


end

app/controllers/registrations_controller.rb
<<<<<<< HEAD
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end
=======
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def account_update_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end

end
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7

app/controllers/shouts_controller.rb
<<<<<<< HEAD
=======

>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7
class ShoutsController < ApplicationController
  before_action :set_shout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /shouts
  # GET /shouts.json
  def index
    @shouts = Shout.all.order("created_at DESC")
    @shout = Shout.new
  end

  # GET /shouts/1
  # GET /shouts/1.json
  def show
  end

  # GET /shouts/new
  def new
<<<<<<< HEAD
    @shout = current_user.shouts.new
=======
<<<<<<< HEAD
    @shout = current_user.shouts.build
=======
    @shout = current_user.shouts.new
>>>>>>> 294d7336c24df0edd0ccf35a7cee0ccca84a468e
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7
  end

  # GET /shouts/1/edit
  def edit
  end

  # POST /shouts
  # POST /shouts.json
  def create
    @shout = current_user.shouts.build(shout_params)

    respond_to do |format|
      if @shout.save
        format.html { redirect_to root_path, notice: 'Shout was successfully created.' }
        format.json { render :show, status: :created, location: @shout }
      else
        format.html { render :new }
        format.json { render json: @shout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shouts/1
  # PATCH/PUT /shouts/1.json
  def update
    respond_to do |format|
      if @shout.update(shout_params)
        format.html { redirect_to @shout, notice: 'Shout was successfully updated.' }
        format.json { render :show, status: :ok, location: @shout }
      else
        format.html { render :edit }
        format.json { render json: @shout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shouts/1
  # DELETE /shouts/1.json
  def destroy
    @shout.destroy
    respond_to do |format|
      format.html { redirect_to shouts_url, notice: 'Shout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shout
      @shout = Shout.find(params[:id])
    end

<<<<<<< HEAD
    # Never trust parameters from the scary internet, only allow the white list through.
    def shout_params
      params.require(:shout).permit(:shout)
    end
end
=======
    def shout_params
      params.require(:shout).permit(:shout)
    end
end
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %>:</strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>
     <%= link_to 'Delete', [comment.post, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@shout, @shout.comments.build]) do |f| %>
<!--
collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
-->
<div class="field">
  <div class="control">
    <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
  </div>
</div>
<%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoutOut</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
     <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      <% end %>
  	<nav class="navbar is-info">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5">ShoutOut</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  		</div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped">
              <p class="control">
<<<<<<< HEAD
              <% if user_signed_in? %>
                <%= link_to 'New ShoutOut', root_path, class: "button is-info is-inverted" %>
              </p>
              
=======
                <%= link_to 'New ShoutOut', root_path, class: "button is-info is-inverted" %>
              </p>
              <% if user_signed_in? %>
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7
                <p class="control">
                  <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                </p>
                <p>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
                </p>
              <% else %>
              <p class="control">
                <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
              </p>
              <% end %>
          </div>
        </div>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/shouts/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name ) %>
            </p>
        </figure>
            <div class="media-content">
                <%= render 'shouts/form' %>
            </div>
    </article>
<% end %>


<% @shouts.each do | shout | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
<%= gravatar_image_tag(shout.user.email, size: 64, alt: shout.user.name ) %>                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong><%= shout.user.name %></strong><br />
                    <small>@<%= shout.user.username %></small><br />
                    <p><%= shout.shout %></p>
                </div>
                    <% if user_signed_in? %>
                        <nav class="level">
                            <div class="level-left is-mobile">
                                <%= link_to shout, class: "level-item" do %>
                                    <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                                <% end %>
                            <%= link_to edit_shout_path(shout), class: "level-item" do %>
                                <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                            <% end %>
                            <%= link_to shout, method: :delete, data: { confirm: "Are you sure you want to delete this shoutout?" 
                            } do %>
                                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                            <% end %>
                        </div>
                    </nav>
                <% end %>
            </div>
        </article>
    </div>
<% end %>
</div>

app/views/shouts/_form.html.erb
<%= simple_form_for(@shout) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :shout, label: "Give a ShoutOut", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Give a shoutout...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/shouts/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">ShoutOuts</p>
						<p class="title is-6"><%= current_user.shouts.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/shouts/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
<<<<<<< HEAD
		<p class="panel-heading">Trending Now</p>
		<a class="panel-block" href="https://www.linkedin.com/in/jmrandolph/" target="_blank">
			Developer for Hire
		</a>
		<a class="panel-block" href="https://docs.google.com/presentation/d/1au4Q-XOOx3i9_BLgN-YHD036pmA6waha5UgCkiJZTZ4/edit?usp=sharing" target="_blank">
			This Great Resume
=======
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7
		</a>
	</nav>
</div>

app/views/shouts/_who-to-follow.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>
	
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
<<<<<<< HEAD
						<strong>Jane Smith</strong>
						<small>@janesmith</small>
=======
						<strong>John Smith</strong>
						<small>@johnsmith</small>
>>>>>>> e5dbff343c8745a2ce35e9af423d8b3543f514c7
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/shouts/edit.html.erb
<div class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <h1 class="title">Editing ShoutOut</h1>
                <%= render 'form', shout: @shout %>
            </div>
        </div>
    </div>
</div>

<nav class="navbar is-fixed-bottom">
    <div class="navbar-menu">
        <div class="navbar-item">
            <div class="field is-grouped">
                <p class="control">
                    <%= link_to 'Cancel', shouts_path, class: "button is-dark" %>
                </p>
            </div>
        </div>
    </nav>

app/views/shouts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
        <%= render 'feed' %>
        <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/shouts/new.html.erb
<div class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <h1 class="title">New ShoutOut</h1>
                <%= render 'form', shout: @shout %>
            </div>
        </div>
    </div>
</div>

<nav class="navbar is-fixed-bottom">
    <div class="navbar-menu">
        <div class="navbar-item">
            <div class="field is-grouped">
                <p class="control">
                    <%= link_to 'Cancel', shouts_path, class: "button is-dark" %>
                </p>
            </div>
        </div>
    </nav>

app/views/shouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shout:</strong>
  <%= @shout.shout %>
</p>

<%= link_to 'Edit', edit_shout_path(@shout) %> |
<%= link_to 'Back', shouts_path %>